-- RE-SYNC project_doc.body FROM THE COMMITTED CLAUDE.md — generated by scripts/sync-project-doc.mjs.
--
-- The row and the committed file are two copies of ONE document (house rule 11 keeps generation off a
-- tracked path, and nothing then reconciles them). test/project-doc-drift.test.mjs fails when they
-- diverge; this closes it in the direction that is reviewable — the committed file wins, because it is
-- the copy that gets diffed, landed and blamed. An edit made only to the row is an edit to the wrong
-- copy: that is ticket #38, where eighteen tools read a containment claim this repo had disproved.
--
-- Idempotent (it sets a known text). A database with no project_doc row is a no-op, correctly: with no
-- row, lib/project-docs.js generates nothing, so there is no second copy to diverge.
-- Snapshot, by nature — see docs/entry-point-doc-source.md for the standing fix and its open decision.
UPDATE project_doc
   SET body = $doc$# CLAUDE.md — start here

**ZEEHIVE** is a deterministic agent-environment orchestrator: it cuts isolated environments
(**xells**), runs agents (**zees**) inside caged containers (**cxells**), and puts a human gate in
front of everything irreversible. It orchestrates itself — work on ZEEHIVE happens in ZEEHIVE xells.

Read this file, then [README.md](README.md). That is the whole orientation. **Everything else in
this repo is reference, not instructions** — see the doc map at the bottom, and read the warning
about `HANDOFF.md` before you open it.

---

## 1. First: work out which surface you are on

The repo is worked on from two places, and they have **different, non-overlapping toolsets**. Nearly
every orientation mistake made here is a zee running the other surface's verbs.

```sh
# One command tells you:
test -n "$ZEEHIVE_XELL_TOKEN" && echo "CXELL (caged zee)" || echo "HOST (or plain checkout)"
```

| | **cxell zee** (almost certainly you) | **host session / human** |
|---|---|---|
| workspace | `/work/repo` — a private clone of YOUR branch | a real checkout of the project |
| docker | **none.** No CLI, no socket | the daemon, contexts, compose |
| host filesystem | **none.** The repo is all you can see | all of it |
| network | egress is OPEN (your provider's API, your own containers, the registries) — the fleet's live **prod DBs** are what is dropped | whatever the machine has |
| verbs | the **`zee`** CLI (§2) | `scripts/xell-*.mjs`, `skill/`, the console, MCP |
| main/master | **not a ref in here** — `git fetch`/`git rebase main` cannot work; use `zee sync` | normal git |
| the API | **TWO servers answer the same paths** — see below | one server, no ambiguity |

If you are in a cxell, **the host column does not exist for you**. `docker`, `docker --context …`,
`scripts/provision-xell.sh`, the `/xell` slash-commands and the MCP server are all real code in this
repo and all unreachable from your cage — by design, not by outage. Do not try to route around it;
the cage is the product working.

### ⚠ Two servers answer the same paths — ask the right one

Same failure family as running the other surface's verbs, and harder to catch, because **nothing
fails**: you get a well-formed answer from a real server that is answering a different question.

| you reach | at | it answers |
|---|---|---|
| **your OWN build** | the app-tier host:port in your binding | *does MY BRANCH have this?* |
| **the real queenzee** | `zee` (→ `host.docker.internal:4700`) | *does the FLEET have this?* |

`zee build` puts YOUR code on your own server, so it has every route your branch adds — including
routes production has never seen. So a `200`, or an auth `401`, from your own server is **not**
evidence that the fleet has shipped anything. One zee reported that a queenzee route 404s, re-probed
its own server, got a well-formed `401`, and was one message from "correcting" a true report into a
false one. If the question is *"does the fleet have this yet"*, probe through `zee` or
`host.docker.internal:4700`, **and send a known-good path alongside as a control** — a bare 404 with
nothing to compare it against cannot tell a missing route from an unreachable server.

## 2. If you are a cxell zee

**Your manual is `.zeehive/harness/memory/cxell-zee-manual.md`, in your own workspace** — every verb,
its gate, and the golden rules. It is authoritative and it is delivered to your xell from the meta-DB
(harness `zee-base`), so it is always current for the queenzee you are talking to. It is deliberately
**not** a file in `docs/`: a checked-in copy would rot the day the API moved. That path is INJECTED,
not tracked (`.gitignore`) — it is there when you Read it and it is not part of any diff you land, so
never commit it and never "restore" it if a merge disagrees with it.

The shape of it:

- **`zee build [server|webapp|all] [--wait]`** — the ONE verb that acts immediately, because
  building your own throwaway containers needs no human. **Commit first** (it builds your commits),
  and run `--wait` in the **background** — never hand-roll a `curl | grep` poll against your own app.
- **Everything else is only a REQUEST** that lands on a human: `zee land` (push to main),
  `zee ship` (deploy prod), `zee prod` / `zee seed` (prod data), `zee done` (finish).
  You never hold the prod lock and you never despawn yourself.
- **`zee sync`** is how you rebase/catch up (the queenzee delivers current main INTO the cage and
  merges it). **`zee db-catchup`** is the same idea one layer down, for your database.
- **`zee status`**, **`zee work`**, **`zee working`**, **`zee tend --reason "…"`** to orient, report
  and ask for a human.

**Commit early and often.** A commit moves only your branch ref — it lands nothing, touches no one,
and it is the only thing protecting your work.

## 3. Running and verifying your change

Your database is your own container (`DATABASE_URL` in `.zeehive.env`, which is **generated** — do
not edit it). It is a throwaway copy: migrate, seed or destroy it freely.

```sh
set -a; . ./.zeehive.env; set +a     # DATABASE_URL + this xell's ports and safety flags

npm install
npm run db:migrate                   # db/migrations/*.sql, forward-only, filename-ordered
npm run server                       # queenzee + API on $PORT
npm run web                          # console on $ZEEHIVE_WEB_PORT
npm run dev                          # both

node test/<name>.test.mjs            # tests are standalone node scripts, no runner
```

There is **no `npm test`**. Each file in `test/` is run directly and prints `✓`/`✗ FAIL` lines; the
integration ones stand up real git repos and throwaway postgres rows against `DATABASE_URL`. Run the
ones your change touches, and add to them the same way — the existing tests document what they cover
in a header comment, and that header is part of the deliverable.

A Zeehive xell inherits **simulate-mode safety defaults** (`zeehive.yml` → `BUILD_MODE`,
`PROVISION_MODE`, `SHIP_MODE` = `simulate`, `POOL_TARGET_READY=0`): the nested queenzee you run is a
subject under test, and every PROVISION, TEARDOWN, BUILD, DEPLOY-FILE and BACKUP path is mode-gated.
That is why your local run provisions nothing.

⚠ It does **not** follow that it "can never touch the real fleet" — that sentence used to be here and
it was not true. Your nested meta-DB is a **CLONE of the real one** (real slugs, container names,
docker contexts, host repo paths), the flags gate ACTIONS and not READS, and in a cxell much of the
rest is inert only because a cage has no docker binary and no host paths — a property of the cage,
not of the code. `proddiff` reads real production databases with no mode gate at all, and one write
path (the ship's migration apply) has none either. The audit, loop by loop, with the read-only versus
write distinction kept separate:
[docs/nested-queenzee-containment.md](docs/nested-queenzee-containment.md).

**"I wrote it" is not verification.** Exercise the real thing in your own containers before you call
the work done.

## 4. Layout

```
db/migrations/   forward-only, filename-ordered SQL. The FOLDER is the truth — never a list in a doc.
                 The manual + spawn briefing zees read are SEEDED here too (into harness `zee-base`),
                 so changing what a zee is told is a MIGRATION, not a doc edit.
server/src/
  api/routes.js  every HTTP route (hooks, claim, the gates, /xell/self/* verbs, SSE stream)
  queenzee/      the loops: pool, intake, monitor, landing + landgate + landingpad, shipgate +
                 shipmigrate, seedgate, reaper, maintenance, dbclone, proddiff, worksync, self
  lib/           provision, cxell driver, git, harness, work-items, remote-git (clone/pull, no
                 push), projects, fleet, notify, agent-docs (every AI provider's entry-point
                 filename) + project-docs + xell-stack (the docs GENERATED into a xell), …
  db/            migrate.js, seed.js  (seed_demo.js is DEAD — see house rules)
web/src/         the console (React + Vite): App.jsx, hive/ (honeycomb canvas), work/ (board+gantt),
                 Landing.jsx · Ship.jsx · ProdData.jsx (the human GATES), ZeeTerminal.jsx, DiffViewer.jsx
hooks/           land-gate-update.sh (the xource push gate), prod-guard.mjs (+ its canary)
scripts/         provisioning/build/ship/land scripts, and `zee` — the ONE copy of the in-cxell CLI
docker/zeehive/  Dockerfile.{server,web,zee-agent}, compose, and the deployment playbook (README.md)
mcp/server.js    MCP server wrapping the API (host surface)
skill/           source of the `/xell*` slash-commands (host surface)
test/            standalone integration tests (see §3)
docs/            specs and rationale (see the doc map)
```

## 5. House rules (learned the hard way — do not relearn them)

1. **No test data.** `server/src/db/seed_demo.js` exists; never run it. Tests clean up what they
   create, in a `finally`, whatever happens.
2. **Never touch a xell you did not create**, and never one you were not given. A past session
   reaped a live zee mid-task and lost real work.
3. **`origin` is off-limits.** Zees land with `git push . HEAD:main` (from a cxell: `zee land`),
   which a git hook on the xource **holds for a human**. Publishing outward is a human's click.
4. **A human marks a xell done**, not the zee.
5. **Builds go through the queenzee** (`zee build`), never ad-hoc docker or compose.
6. **Prod data is never a default** — `db-shared-prod` is the live database and must be asked for.
   When the job is really "rows into prod", that is `zee seed`, not a bind.
7. **Names, containers, couplings and status are DATA** — they live in the meta-DB and the API
   resolves them live. Never restate one in a doc; a container name written into prose is stale at
   the next rebuild, and one of those sent zees at an exited husk for weeks.
8. **What a zee is told is versioned like code.** The manual, the briefing and the CLI usage must
   move together (`test/cxell-cli-drift.test.mjs` fails the build if they drift).
9. **A migration edits harness memory BY PATH, through the helper.** `harness_memory_put(harness_key,
   path, text)` (076) replaces the entry when present, appends when absent, keeps every sibling;
   `harness_memory_get` reads one back for an anchored edit. Never hand-roll
   `jsonb_set(bundle,'{memory}', …)`: six migrations rebuilt that array from `memory->0` and deleted
   a memory file out of the LIVE meta-DB — invisible on a fresh database, which is every cxell's.
   `test/harness-memory-migrations.test.mjs` fails anything newer that tries.
10. **A harness lives ENTIRELY in the meta-DB, and so does a project's entry-point doc.** There is no
   `harnesses/` folder: the row carries the personality, the skills, the memory (080) and the badge
   SVG (082), it is edited in the console's harness manager or by migration, and the queenzee
   GENERATES the files it injects into a xell (stamped as generated). `lib/harness.js` reads no
   filesystem, so a harness cannot be "missing files" on any project or in any container. Project
   entry-point docs work the same way (081, 083, `lib/project-docs.js`) and are never written over a
   path the project has committed. Do not reintroduce a repo copy of either: the folder-and-row split
   shipped a fleet of manager zees with no manual at all, and hid a migration's edit behind a hash
   that said the two agreed.
11. **A project's entry-point doc is ONE text, not one file per tool.** `project_doc.body` is the
   source of truth and `targets` says which providers receive it; the FILENAMES are a registry in
   code (`lib/agent-docs.js` — `CLAUDE.md`, `AGENTS.md`, `GEMINI.md`, `.github/copilot-instructions.md`,
   `.cursor/rules/*.mdc`, …), each entry carrying the vendor doc that settles it. Never add a second
   row to give another tool the same instructions — tick its provider. Every generated file also ends
   with THAT xell's stack, generated per xell (`lib/xell-stack.js`): that is house rule 7 for an agent
   that has no `zee status` to ask.

## 6. Doc map — which file answers what

| you want | read |
|---|---|
| what ZEEHIVE is, the vocabulary, the gates | [README.md](README.md) |
| **your verbs as a caged zee** | `.zeehive/harness/memory/cxell-zee-manual.md` (in your xell) |
| a zee that runs other zees | [docs/manager-zees.md](docs/manager-zees.md) |
| tickets, work items, the board | [docs/work-tracker.md](docs/work-tracker.md) (nouns) · [docs/work-tracker-verbs.md](docs/work-tracker-verbs.md) (verbs) |
| harnesses (persona/skill/memory layers) — and where their text lives | [docs/harness-proposal.md](docs/harness-proposal.md) (§3.1) |
| the role-specialised worker personas (Scout, Builder, Reviewer, …) | [docs/dev-crew.md](docs/dev-crew.md) |
| the manager harness that runs that crew | [docs/dev-crew-lead.md](docs/dev-crew-lead.md) |
| how a zee's db catches up to prod's schema | [docs/schema-catchup-plan.md](docs/schema-catchup-plan.md) |
| a db chip says DRIFTED and you need to know why | [docs/schema-drift-triage.md](docs/schema-drift-triage.md) |
| why a fresh restore still shows drift, and what a backup does **not** prove | [docs/data-completeness-check.md](docs/data-completeness-check.md) |
| projects, manifests, deploy sites | [docs/deploy-topology-spec.md](docs/deploy-topology-spec.md) |
| onboarding the `mardale-prod-alt` docker context (SSH over Cloudflare Access) | [docs/onboard-mardale-prod-alt.md](docs/onboard-mardale-prod-alt.md) |
| what a NESTED queenzee can actually reach (loop by loop, read vs write) | [docs/nested-queenzee-containment.md](docs/nested-queenzee-containment.md) |
| `config.repoRoot` = the server's OWN tree, never a project's files | [docs/repo-root-audit.md](docs/repo-root-audit.md) |
| **this file has a second copy** (`project_doc.body`) — which one is the source | [docs/entry-point-doc-source.md](docs/entry-point-doc-source.md) |
| what runs where in production, and the cutover | [docker/zeehive/README.md](docker/zeehive/README.md) |
| **why** a gate is shaped the way it is; traps already paid for | [HANDOFF.md](HANDOFF.md) — **history, not instructions** |

⚠ **About `HANDOFF.md`.** It is the rationale of record — the reasoning behind the landing gate, the
ship gate, the prod guard, and a list of expensive mistakes worth not repeating. Code comments cite
it. But it was written for a **host** session on one Windows machine in an earlier era of this repo,
and zees have repeatedly read it as their orientation and gone chasing paths, containers and verbs
that do not exist here. **This file is your orientation; HANDOFF.md is background reading.** Anything
in it that names a drive letter, a docker context or a machine is history — check before you trust.
$doc$,
       updated_at = now()
 WHERE project_id = (SELECT id FROM project WHERE lower(name) = 'zeehive' ORDER BY created_at LIMIT 1)
   AND cardinality(targets) > 0;
