-- WIREGUARD MESH (docs/common-xell-network-plan.md, Decision 5.4) — ZEEHIVE OPERATED.
--
-- The human asked for a way to DOWNLOAD a WireGuard config to join the network. This migration
-- gives the meta-DB the shape for a ZEEHIVE-operated WG mesh:
--
--   wireguard_server  — ONE row: the WG interface the queenzee (or a designee) runs. It is where
--                       every peer dials. A human who wants to join gets a config whose
--                       [Interface] is their fresh keypair and whose [Peer] is this server.
--   wireguard_peer    — one row PER human/machine that joins: their public key, an allocated
--                       tunnel IP, and the server's ENDPOINT (host:port) baked into their config
--                       at issue time. The row is the durable record of "we minted a keypair and
--                       handed this peer a config"; the PRIVATE key lives ONLY in the config
--                       served once at download (never stored here — see the download endpoint).
--
-- The WG SERVER's own keys are generated by the queenzee the first time it stands the mesh up
-- (lib/wireguard.js) and stored here so the interface can be rebuilt from the same identity.
--
-- Keys are Curve25519, which Node's crypto generates natively (verified: x25519 JWK export gives
-- the 32-byte base64 keys WG uses). No wireguard-tools dependency needed to MINT configs; actually
-- RUNNING the interface is the fleet's docker/wg responsibility, not this repo's.
CREATE TABLE IF NOT EXISTS wireguard_server (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id    uuid NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  -- the WG interface's own identity
  private_key   text NOT NULL,            -- base64, 32 bytes — kept so the mesh can be rebuilt
  public_key    text NOT NULL,            -- derived from private_key
  -- where peers dial (the server's endpoint, host:port)
  endpoint      text NOT NULL,            -- e.g. "10.2.0.16:51820" or a tunnel host
  -- the interface's address and netmask
  address       text NOT NULL,            -- e.g. "10.8.0.1/24"
  listen_port   integer NOT NULL DEFAULT 51820,
  -- the docker context that RUNS the WG container (null = this machine / default)
  docker_ctx    text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- One peer = one human/machine that joined (or may join) the mesh.
CREATE TABLE IF NOT EXISTS wireguard_peer (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  server_id     uuid NOT NULL REFERENCES wireguard_server(id) ON DELETE CASCADE,
  -- what this peer is — a human's laptop, a machine, another docker host
  name          text NOT NULL,
  public_key    text NOT NULL UNIQUE,     -- the peer's own WG public key
  -- the tunnel IP allocated to this peer (server side: Address = its own; here: the AllowedIPs
  -- on the server and the address on the peer). The server hands out 10.8.0.2.. /24 by default.
  address       text NOT NULL UNIQUE,     -- e.g. "10.8.0.2/32"
  -- the server's endpoint AT ISSUE TIME — captured so a peer config is self-contained even if the
  -- server's endpoint later changes (an old config keeps dialing the old address).
  endpoint_snapshot text NOT NULL,
  -- optional DNS the peer config carries
  dns           text,
  -- who issued it / when, for audit
  created_by    text NOT NULL DEFAULT 'human@console',
  created_at    timestamptz NOT NULL DEFAULT now(),
  -- a peer that was never downloaded is harmless; one that was is a live tunnel participant.
  downloaded_at timestamptz
);

-- One server per project — a project owns its mesh. (The fleet's dev + prod may want separate
-- meshes; a project is the natural scope.)
CREATE UNIQUE INDEX IF NOT EXISTS wireguard_server_project_uq ON wireguard_server (project_id);

-- Peers are per-server, ordered by issue time.
CREATE INDEX IF NOT EXISTS wireguard_peer_server_idx ON wireguard_peer (server_id, created_at);
