// PROJECT ENTRY-POINT DOCS — the AGENTS.md/CLAUDE.md a zee reads first, owned by the meta-DB.
//
// A cxell zee opens the project's entry-point markdown before it designs anything. Those files were
// whatever the repo happened to have committed: nothing at all for a project that never wrote one, no
// way to give a fleet-wide instruction without a commit, and one file per provider convention
// (AGENTS.md, CLAUDE.md, …) to keep in step by hand. Migration 081 moves them where the harnesses
// already live — the meta-DB — and the queenzee GENERATES them into a xell when a zee is assigned.
//
// The thing that must not break is the repo. A generated file landing on top of a committed CLAUDE.md
// would replace the project's own instructions with an operator's, dirty every xell's worktree, and
// put a file nobody wrote into a landing diff. So this asserts, against the real DB and a real git
// repo standing in for a cxell's /work/repo:
//   1. the PATH RULES (relative, .md, no '..', not .git/ or .zeehive/) and one row per path;
//   2. the generated text: the meta-DB stamp first, the body verbatim, disabled/empty rows skipped;
//   3. the TRACKED-FILE REFUSAL, run against real `git ls-files` — the exact script the injector
//      executes inside the cage, so this is the decision itself and not a paraphrase of it;
//   4. and that an untracked write is git-EXCLUDED, so the artefact can never travel into a commit.
// Everything it creates is deleted in a finally, whatever happens.
import { randomUUID } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const { q, one, pool } = await import('../server/src/db/pool.js');
const P = await import('../server/src/lib/project-docs.js');

let failures = 0;
const ok = (cond, msg) => { console.log(`  ${cond ? '✓' : '✗ FAIL'} ${msg}`); if (!cond) failures++; };

const tag = randomUUID().slice(0, 8);
const tmp = mkdtempSync(join(tmpdir(), 'projdocs-'));
const repo = join(tmp, 'work-repo');
const git = (...a) => execFileSync('git', ['-C', repo, ...a], { encoding: 'utf8' }).trim();
let projId = null;

try {
  projId = (await one(`INSERT INTO project (name, repo_root, main_branch) VALUES ($1,$2,'master') RETURNING id`,
    [`zt-docs-${tag}`, join(tmp, 'src')])).id;

  // ── 1. the path rules ───────────────────────────────────────────────────────────────────────
  console.log('\n── which paths a generated doc may claim ──');
  for (const good of ['AGENTS.md', 'CLAUDE.md', 'docs/agents/ONBOARDING.md', './AGENTS.md']) {
    ok(P.validateDocPath(good).ok, `allowed: ${good}`);
  }
  for (const [bad, why] of [['/etc/passwd', 'absolute'], ['../outside.md', 'climbs out'],
                            ['a/../../b.md', 'climbs out mid-path'], ['AGENTS.txt', 'not markdown'],
                            ['.git/hooks/x.md', 'inside .git'], ['.zeehive/harness/memory/x.md', 'harness space'],
                            ['', 'empty']]) {
    const v = P.validateDocPath(bad);
    ok(!v.ok, `refused (${why}): ${JSON.stringify(bad)} — ${v.reason}`);
  }
  ok(P.validateDocPath('./AGENTS.md').path === 'AGENTS.md', "a leading './' is normalised away");

  const agents = await P.createProjectDoc(projId, {
    rel_path: 'AGENTS.md', title: 'House rules', body: `# House rules ${tag}\n\nRun the tests.\n` });
  ok(!!agents.id && agents.rel_path === 'AGENTS.md', 'a doc is created for the project');
  let dup = null;
  try { await P.createProjectDoc(projId, { rel_path: 'agents.md', body: 'x' }); }
  catch (e) { dup = e.message; }
  ok(/already has a doc/.test(dup || ''),
     `a second row for the same path is refused, case-insensitively ("${(dup || '').slice(0, 44)}…")`);
  let badPath = null;
  try { await P.createProjectDoc(projId, { rel_path: '../escape.md', body: 'x' }); }
  catch (e) { badPath = e.message; }
  ok(/bad path/.test(badPath || ''), 'and so is a path outside the repo, at the authoring surface');

  // ── 2. what gets generated ──────────────────────────────────────────────────────────────────
  console.log('\n── the files generated from those rows ──');
  const disabled = await P.createProjectDoc(projId, { rel_path: 'CLAUDE.md', body: 'disabled\n', enabled: false });
  const blank = await P.createProjectDoc(projId, { rel_path: 'docs/EMPTY.md', body: '   \n' });
  const files = await P.projectDocFiles(projId);
  ok(files.length === 1 && files[0].relPath === 'AGENTS.md',
     `only the enabled, non-empty rows are generated (${files.map((f) => f.relPath).join(', ') || 'none'})`);
  ok(files[0].text.startsWith('<!-- GENERATED by ZEEHIVE from the meta-DB'),
     'the file OPENS with the stamp — a reader sees it before the content');
  ok(files[0].text.includes('`AGENTS.md`') && /Editing THIS copy changes nothing/.test(files[0].text),
     'which names the path and says an edit here is overwritten');
  ok(/Docs tab/.test(files[0].text), 'and where the source actually is');
  ok(files[0].text.includes(`# House rules ${tag}`), 'the body is carried verbatim');

  await P.updateProjectDoc(disabled.id, { enabled: true });
  ok((await P.projectDocFiles(projId)).length === 2, 'enabling a row adds its file');
  await P.updateProjectDoc(disabled.id, { body: '' });
  ok((await P.projectDocFiles(projId)).length === 1, 'and emptying its body takes it out again (a doc that says nothing is worse than none)');
  ok((await P.deleteProjectDoc(blank.id)).deleted, 'a doc can be deleted');

  // ── 3. the tracked-file refusal, decided by real git ────────────────────────────────────────
  // This runs the SAME shell the injector execs inside the cxell (lib/cxell.js), against a real repo:
  // the decision itself, not a description of it. There is no docker in a cxell to exec into, and the
  // git behaviour is the whole point.
  console.log('\n── a generated doc never overwrites a file the project committed ──');
  mkdirSync(repo, { recursive: true });
  git('init', '-q', '-b', 'master'); git('config', 'user.email', 't@t'); git('config', 'user.name', 't');
  writeFileSync(join(repo, 'CLAUDE.md'), '# the project\'s OWN committed instructions\n');
  git('add', '-A'); git('commit', '-qm', 'the repo brings its own CLAUDE.md');

  // the injector's script, verbatim from lib/cxell.js — kept in one place so a change there is
  // caught here rather than diverging quietly
  const cxellSrc = readFileSync('server/src/lib/cxell.js', 'utf8');
  const block = cxellSrc.slice(cxellSrc.indexOf('export async function writeGeneratedDocIntoCxell'),
                               cxellSrc.indexOf('export async function removeCxell'));
  const steps = [...block.matchAll(/^\s*'([^']*)',$/gm)].map((m) => m[1])
    .filter((l) => l && !l.startsWith('exec') && l !== '-i' && l !== 'bash' && l !== '-lc');
  ok(steps.includes('cd /work/repo') && steps.some((l) => /git ls-files --error-unmatch/.test(l)),
     'the injector really asks git before writing (its script is read out of the source here)');
  // the target path is interpolated by the caller (shell-quoted there), so it is supplied here the
  // same way: everything else is the source's own lines, in the source's own order.
  ok(/P=\$\{sq\(safe\)\}/.test(block), 'and the path it asks about is the shell-quoted target');
  const run = (relPath, text) => {
    const script = [`cd ${repo}`, `P='${relPath}'`,
      ...steps.filter((l) => l !== 'cd /work/repo')].join('\n');
    const r = spawnSync('bash', ['-lc', script], { input: text, encoding: 'utf8' });
    return { verdict: String(r.stdout || '').trim().split('\n').pop(), status: r.status, err: r.stderr };
  };

  const tracked = run('CLAUDE.md', 'GENERATED — must not land\n');
  ok(tracked.verdict === 'TRACKED', `a tracked path answers TRACKED (${tracked.verdict}) and is not written`);
  ok(readFileSync(join(repo, 'CLAUDE.md'), 'utf8').includes("project's OWN"),
     "the project's committed file is byte-for-byte untouched");
  ok(git('status', '--porcelain') === '', 'and the worktree is still clean — nothing to dirty a landing diff');

  const fresh = run('AGENTS.md', `${P.docBanner('AGENTS.md')}\n\ngenerated body ${tag}\n`);
  ok(fresh.verdict === 'WROTE', `an untracked path is written (${fresh.verdict})`);
  ok(readFileSync(join(repo, 'AGENTS.md'), 'utf8').includes(`generated body ${tag}`), 'with the generated content');

  // ── 4. …and excluded, so it cannot travel into a commit ─────────────────────────────────────
  ok(existsSync(join(repo, '.git/info/exclude'))
     && readFileSync(join(repo, '.git/info/exclude'), 'utf8').split('\n').includes('AGENTS.md'),
     'the written path is added to .git/info/exclude');
  ok(git('status', '--porcelain') === '',
     'so `git status` stays clean with the generated file present — it can never land in a diff');
  const again = run('AGENTS.md', `regenerated ${tag}\n`);
  ok(again.verdict === 'WROTE' && readFileSync(join(repo, 'AGENTS.md'), 'utf8').includes(`regenerated ${tag}`),
     'regenerating it overwrites the artefact (the row is the source, every time)');
  ok(readFileSync(join(repo, '.git/info/exclude'), 'utf8').split('\n').filter((l) => l === 'AGENTS.md').length === 1,
     'and the exclude entry is not appended twice');

  // a doc in a SUBDIRECTORY: the injector must create it
  const nested = run('docs/agents/ONBOARDING.md', 'nested\n');
  ok(nested.verdict === 'WROTE' && existsSync(join(repo, 'docs/agents/ONBOARDING.md')),
     'a doc in a subdirectory has its directories created');

  // ── an edit reaches the zees ALREADY RUNNING ────────────────────────────────────────────────
  // Same rule a harness save obeys: "new zees only" is the failure that left a fleet briefed on stale
  // text. In THIS cxell PROVISION_MODE is simulate (a nested queenzee's fleet rows are the real
  // fleet's), so the correct behaviour is to REPORT the live xells it would have regenerated in and
  // exec into none of them — and to say which, never a silent skip.
  console.log('\n── saving a doc pushes it into live zees (reported, not executed, in simulate) ──');
  const { recentLogs } = await import('../server/src/lib/logbus.js');
  const xource = await one(`INSERT INTO xource (project_id, ref) VALUES ($1,'master') RETURNING id`, [projId]);
  const liveXell = await one(
    `INSERT INTO xell (project_id, xource_id, slug, branch, worktree_path, status, is_pooled)
       VALUES ($1,$2,$3,'spinoff/zt-doc','/tmp/zt-doc','working',false) RETURNING id, slug`,
    [projId, xource.id, `zt-doclive-${tag}`]);
  await q(`INSERT INTO zee (xell_id, runtime_id, attach_mode, status, entrypoint, viewer_kind)
           VALUES ($1, (SELECT id FROM agent_runtime LIMIT 1), 'headless-spawn', 'working', 'cxell-cli', 'ssh-terminal')`,
    [liveXell.id]);
  const before = recentLogs(300).length;
  await P.updateProjectDoc(agents.id, { body: `# edited ${tag}\n` });
  const said = recentLogs(300).slice(before).filter((l) => l.scope === 'project-doc').map((l) => l.msg);
  ok(said.some((m) => /NOT pushed into 1 live xell/.test(m) && /PROVISION_MODE=/.test(m)),
     'the push obeys PROVISION_MODE and says so rather than execing into another zee\'s cxell');
  ok(said.some((m) => m.includes(liveXell.slug)),
     'and NAMES the live xell it would have regenerated in — a report, never a silent skip');

  // ── the rows die with the project ───────────────────────────────────────────────────────────
  console.log('\n── lifecycle ──');
  const n = (await P.listProjectDocs(projId)).length;
  ok(n === 2, `the project has its docs listed (${n})`);
  await q(`DELETE FROM zee WHERE xell_id=$1`, [liveXell.id]);
  await q(`DELETE FROM project WHERE id=$1`, [projId]);
  const after = await q(`SELECT count(*)::int AS n FROM project_doc WHERE project_id=$1`, [projId]);
  ok(after[0].n === 0, 'and they are deleted with the project (ON DELETE CASCADE)');
  projId = null;
} finally {
  if (projId) await q(`DELETE FROM project WHERE id=$1`, [projId]).catch(() => {});
  try { rmSync(tmp, { recursive: true, force: true }); } catch { /* */ }
  await pool.end().catch(() => {});
}

console.log(failures ? `\n${failures} FAILED` : '\nall good');
process.exit(failures ? 1 : 0);
