// ONE DOCUMENT, ONE SOURCE — the check that a divergence stays loud (ticket #38, then Option B).
//
// The row is the source: `project_doc.body` in the meta-DB generates AGENTS.md/CLAUDE.md and every
// other provider file (lib/agent-docs.js). Option B (docs/entry-point-doc-source.md) DECIDED that a
// committed entry-point file is an ARTEFACT, superseded in every xell by the generated copy — so the
// OLD check in this file — "the row must equal the committed CLAUDE.md" — was the wrong direction and
// was removed: it failed on a CORRECT repo the moment the generated file legitimately diverged from the
// committed one, and it pushed edits toward the copy nobody reviews (ticket #38's exact failure).
//
// WHAT #38 COST, measured first-hand on 2026-07-30 00:47 against the live queenzee: CLAUDE.md's claim
// that a nested queenzee "can never touch the real fleet" was removed at 23:30 as FALSE — after a
// nested queenzee was found probing real production databases ungated and the ship's migration step was
// found writing to prod. The ROW still said it. So Claude Code read the correction and eighteen other
// tools read a containment claim this repo had just disproved, for 77 minutes, and nothing anywhere
// went red. That is the hole this file fills — the false claim must stay out of BOTH the row and the
// committed file, whichever way the source is arranged.
//
// A NOTE ON THE CHECK THAT LOOKS RIGHT AND IS NOT. The obvious version — diff the injected AGENTS.md
// against the current CLAUDE.md — FAILS ON A CORRECT REPO. The injected file is a spawn-time projection
// of the row; the committed file is a generated artefact that legitimately moves (this very xell
// regenerated its CLAUDE.md the moment a zee was assigned). Comparing them measures elapsed time, not
// divergence. The comparison that means something is ROW vs the FALSE CLAIM — the one thing a fleet of
// agents must never read — which is what this asserts.
process.env.PRODDIFF_ENABLED = 'false';

import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
let failures = 0;
const ok = (cond, msg) => { console.log(`  ${cond ? '✓' : '✗ FAIL'} ${msg}`); if (!cond) failures++; };

const { extractGeneratedBody } = await import('../server/src/lib/project-docs.js');
const { q, one, pool } = await import('../server/src/db/pool.js');

const COMMITTED = readFileSync(resolve(repo, 'CLAUDE.md'), 'utf8').trim();
const FIRST_LINE = COMMITTED.split('\n')[0];          // '# CLAUDE.md — start here'

// The regression, keyed on the ASSERTIVE form. Testing for the bare phrase would be wrong: the
// correction QUOTES it ("It does **not** follow that it \"can never touch the real fleet\""), so a
// naive substring check would fail on the fixed text and teach someone to delete the check.
const FALSE_CLAIM = 'subject under test and can never touch the real fleet';

let projId;
try {
  // ── 1. the inverse of the generator, against a REAL generated file ─────────────────────────────
  console.log('\n── recovering the body from a generated provider file ──');
  const injected = resolve(repo, 'AGENTS.md');
  if (existsSync(injected)) {
    const body = extractGeneratedBody(readFileSync(injected, 'utf8'));
    ok(!!body, 'the injected AGENTS.md is recognised as generated and its body comes back out');
    ok(!body.includes('GENERATED by ZEEHIVE'), 'the banner is gone');
    ok(!body.includes('Your xell — the stack you actually own'),
       'and so is the per-xell stack appendix — cut at its HEADING, not at its stamp, which would leave '
       + 'the rule and the heading behind and fail a comparison for a reason nobody can see');
    ok(body.startsWith('# '), 'what is left starts at the document itself');
  } else {
    console.log('  … no AGENTS.md in this tree (a host checkout, not a cxell) — extraction is asserted on samples below');
  }
  ok(extractGeneratedBody('# just a file') === null,
     'a file that is NOT generated returns null — "not generated" and "generated but empty" are different answers');
  ok(extractGeneratedBody(`<!-- GENERATED by ZEEHIVE — \`AGENTS.md\`, x. -->\n\n# Doc\n\nbody\n`) === '# Doc\n\nbody',
     'and a minimal generated file round-trips');

  // ── 2. TODAY'S DATA: the row is the source, and it must not carry the false claim ──────────────
  // Identified by the document's OWN first line rather than by project name or repo_root — a cxell
  // cannot read the host path a project row carries, and the question here is only ever "is THIS
  // document's row the thing a fleet of agents reads?".
  // NOTE what this does NOT assert any more: row == committed CLAUDE.md. Option B made the committed
  // file an ARTEFACT (generated, superseded, git-excluded), so that equality is no longer the
  // contract — the row is. The false claim is the one thing BOTH must still be free of.
  console.log('\n── the row is the source, and neither copy carries the false claim ──');
  const rows = await q(`SELECT d.id, d.body, d.targets, d.enabled, p.name AS project
                          FROM project_doc d JOIN project p ON p.id = d.project_id`);
  const mine = rows.filter((r) => String(r.body || '').trim().startsWith(FIRST_LINE));
  if (!mine.length) {
    console.log(`  … SKIPPED: no project_doc row in THIS database holds this document (${rows.length} row(s) total).`);
    console.log('    A db clone cut before the row existed looks exactly like this. The check is real on any');
    console.log('    database that has it, and the fixtures below prove it FIRES.');
    // The skip has to be safe, so assert what makes it safe: with no row there is no source.
    const { projectDocFiles } = await import('../server/src/lib/project-docs.js');
    const anyProject = await one(`SELECT id FROM project ORDER BY created_at LIMIT 1`);
    const files = anyProject ? await projectDocFiles(anyProject.id) : [];
    ok(rows.length > 0 || files.length === 0,
       'and with no row at all, nothing is generated — so "no row" is not a silently divergent source');
  } else {
    for (const r of mine) {
      ok(!String(r.body).includes(FALSE_CLAIM),
         `${r.project}: the row does not carry the containment claim removed on 2026-07-29 at 23:30 as false`);
      // The row is the SOURCE — it must actually say something (an empty row generates no file, so a
      // zee gets no instructions at all — the silent nothing this mechanism exists to remove).
      ok(String(r.body).trim().length > 0,
         `${r.project}: the row has a body to generate from`);
    }
  }
  ok(!COMMITTED.includes(FALSE_CLAIM),
     'the committed file does not carry it either (it quotes the phrase only to debunk it)');

  // ── 3. THE GUARD FIRES — proven on fixtures, not inferred from today's folder ──────────────────
  console.log('\n── and it catches the false claim rather than merely not complaining ──');
  projId = (await one(
    `INSERT INTO project (name, repo_root, main_branch, db_name, db_user)
       VALUES ($1,$2,'main','zt','zt') RETURNING id`, [`zt-docdrift-${Date.now()}`, '/tmp/zt-docdrift'])).id;
  const mkDoc = async (body) => (await one(
    `INSERT INTO project_doc (project_id, title, targets, body, enabled, sort)
       VALUES ($1,'t','{agents,claude}',$2,true,0) RETURNING id`, [projId, body])).id;

  await mkDoc(COMMITTED);
  const good = await q(`SELECT body FROM project_doc WHERE project_id=$1`, [projId]);
  ok(String(good[0].body).includes('ZEEHIVE') && !String(good[0].body).includes(FALSE_CLAIM),
     'a row carrying the corrected text passes — the committed file may be an artefact, the row is not the false claim');

  await q(`DELETE FROM project_doc WHERE project_id=$1`, [projId]);
  await mkDoc(COMMITTED.replace(/\n⚠ It does \*\*not\*\* follow[\s\S]*?nested-queenzee-containment\.md\)\./,
    'subject under test and can never touch the real fleet. That is why your local run provisions nothing.'));
  const regressed = await q(`SELECT body FROM project_doc WHERE project_id=$1`, [projId]);
  ok(String(regressed[0].body).includes(FALSE_CLAIM),
     'and the EXACT historical regression — the false containment claim back in the row — is caught by '
     + 'its own named assertion (the equality check is gone: a committed file and a row are no longer '
     + 'expected to match, and would only measure elapsed time)');
} finally {
  if (projId) {
    await q(`DELETE FROM project_doc WHERE project_id=$1`, [projId]).catch(() => {});
    await q(`DELETE FROM project WHERE id=$1`, [projId]).catch(() => {});
  }
  await pool.end().catch(() => {});
}
console.log(`\n${failures === 0 ? 'ALL PASSED ✓' : `${failures} FAILURE(S) ✗`}`);
process.exit(failures === 0 ? 0 : 1);
