// ONE DOCUMENT, TWO COPIES — the check that makes the next divergence loud (ticket #38).
//
// A project's entry-point instructions live in `project_doc.body` in the meta-DB, which generates
// AGENTS.md and every other provider file (lib/agent-docs.js). But house rule 11 says generation NEVER
// writes over a git-tracked path — so a repo that has COMMITTED its own CLAUDE.md ends up with two
// copies of one document: the committed file, and the row. Nothing keeps them in step but a person
// remembering, and people stop remembering.
//
// WHAT IT COST, measured first-hand on 2026-07-30 00:47 against the live queenzee: CLAUDE.md's claim
// that a nested queenzee "can never touch the real fleet" was removed at 23:30 as FALSE — after a
// nested queenzee was found probing real production databases ungated and the ship's migration step was
// found writing to prod. The ROW still said it. So Claude Code read the correction and eighteen other
// tools read a containment claim this repo had just disproved, for 77 minutes, and nothing anywhere
// went red. That is the hole this file fills.
//
// A NOTE ON THE CHECK THAT LOOKS RIGHT AND IS NOT. The obvious version — diff the injected AGENTS.md
// against the current CLAUDE.md — FAILS ON A CORRECT REPO. The injected file is a spawn-time projection
// of the row; the committed file legitimately moves during a xell's life (this very xell edited CLAUDE.md
// two hours after its AGENTS.md was written). Comparing them measures elapsed time, not divergence. The
// comparison that means something is ROW vs COMMITTED FILE, which is what this asserts.
process.env.PRODDIFF_ENABLED = 'false';

import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
let failures = 0;
const ok = (cond, msg) => { console.log(`  ${cond ? '✓' : '✗ FAIL'} ${msg}`); if (!cond) failures++; };

const { extractGeneratedBody } = await import('../server/src/lib/project-docs.js');
const { q, one, pool } = await import('../server/src/db/pool.js');

const COMMITTED = readFileSync(resolve(repo, 'CLAUDE.md'), 'utf8').trim();
const FIRST_LINE = COMMITTED.split('\n')[0];          // '# CLAUDE.md — start here'

// The regression, keyed on the ASSERTIVE form. Testing for the bare phrase would be wrong: the
// correction QUOTES it ("It does **not** follow that it \"can never touch the real fleet\""), so a
// naive substring check would fail on the fixed text and teach someone to delete the check.
const FALSE_CLAIM = 'subject under test and can never touch the real fleet';

let projId;
try {
  // ── 1. the inverse of the generator, against a REAL generated file ─────────────────────────────
  console.log('\n── recovering the body from a generated provider file ──');
  const injected = resolve(repo, 'AGENTS.md');
  if (existsSync(injected)) {
    const body = extractGeneratedBody(readFileSync(injected, 'utf8'));
    ok(!!body, 'the injected AGENTS.md is recognised as generated and its body comes back out');
    ok(!body.includes('GENERATED by ZEEHIVE'), 'the banner is gone');
    ok(!body.includes('Your xell — the stack you actually own'),
       'and so is the per-xell stack appendix — cut at its HEADING, not at its stamp, which would leave '
       + 'the rule and the heading behind and fail a comparison for a reason nobody can see');
    ok(body.startsWith('# '), 'what is left starts at the document itself');
  } else {
    console.log('  … no AGENTS.md in this tree (a host checkout, not a cxell) — extraction is asserted on samples below');
  }
  ok(extractGeneratedBody('# just a file') === null,
     'a file that is NOT generated returns null — "not generated" and "generated but empty" are different answers');
  ok(extractGeneratedBody(`<!-- GENERATED by ZEEHIVE — \`AGENTS.md\`, x. -->\n\n# Doc\n\nbody\n`) === '# Doc\n\nbody',
     'and a minimal generated file round-trips');

  // ── 2. TODAY'S DATA: the row must equal the committed file ─────────────────────────────────────
  // Identified by the document's OWN first line rather than by project name or repo_root — a cxell
  // cannot read the host path a project row carries, and the question here is only ever "is THIS
  // document's row in step with THIS document?".
  console.log('\n── the row and the committed file are the same document ──');
  const rows = await q(`SELECT d.id, d.body, d.targets, d.enabled, p.name AS project
                          FROM project_doc d JOIN project p ON p.id = d.project_id`);
  const mine = rows.filter((r) => String(r.body || '').trim().startsWith(FIRST_LINE));
  if (!mine.length) {
    console.log(`  … SKIPPED: no project_doc row in THIS database holds this document (${rows.length} row(s) total).`);
    console.log('    A db clone cut before the row existed looks exactly like this. The check is real on any');
    console.log('    database that has it, and the fixtures below prove it FIRES.');
    // The skip has to be safe, so assert what makes it safe: with no row there is no second copy.
    const { projectDocFiles } = await import('../server/src/lib/project-docs.js');
    const anyProject = await one(`SELECT id FROM project ORDER BY created_at LIMIT 1`);
    const files = anyProject ? await projectDocFiles(anyProject.id) : [];
    ok(rows.length > 0 || files.length === 0,
       'and with no row at all, nothing is generated — so "no row" is not a silently divergent copy');
  } else {
    for (const r of mine) {
      ok(String(r.body).trim() === COMMITTED,
         `${r.project}: project_doc.body is byte-identical to the committed CLAUDE.md `
         + `— if this is red, the fix is one command: \`zee migration-number\` then \`node scripts/sync-project-doc.mjs <NNN>\`. `
         + `Never the other direction: an edit that exists only in the row is an edit to the copy nobody reviews, which IS ticket #38`);
      ok(!String(r.body).includes(FALSE_CLAIM),
         `${r.project}: and it does not carry the containment claim removed on 2026-07-29 at 23:30 as false`);
    }
  }
  ok(!COMMITTED.includes(FALSE_CLAIM),
     'the committed file does not carry it either (it quotes the phrase only to debunk it)');

  // ── 3. THE GUARD FIRES — proven on fixtures, not inferred from today's folder ──────────────────
  console.log('\n── and it catches a divergence rather than merely not complaining ──');
  projId = (await one(
    `INSERT INTO project (name, repo_root, main_branch, db_name, db_user)
       VALUES ($1,$2,'main','zt','zt') RETURNING id`, [`zt-docdrift-${Date.now()}`, '/tmp/zt-docdrift'])).id;
  const mkDoc = async (body) => (await one(
    `INSERT INTO project_doc (project_id, title, targets, body, enabled, sort)
       VALUES ($1,'t','{agents,claude}',$2,true,0) RETURNING id`, [projId, body])).id;

  await mkDoc(COMMITTED);
  const same = await q(`SELECT body FROM project_doc WHERE project_id=$1`, [projId]);
  ok(String(same[0].body).trim() === COMMITTED, 'an in-step row compares equal');

  await q(`DELETE FROM project_doc WHERE project_id=$1`, [projId]);
  await mkDoc(COMMITTED.replace('# CLAUDE.md — start here', '# CLAUDE.md — start here\n\nan edit made only to the row'));
  const drifted = await q(`SELECT body FROM project_doc WHERE project_id=$1`, [projId]);
  ok(String(drifted[0].body).trim() !== COMMITTED,
     'a row with ONE line the file does not have is caught — which is the whole failure mode');

  await q(`DELETE FROM project_doc WHERE project_id=$1`, [projId]);
  await mkDoc(COMMITTED.replace(/\n⚠ It does \*\*not\*\* follow[\s\S]*?nested-queenzee-containment\.md\)\./,
    'subject under test and can never touch the real fleet. That is why your local run provisions nothing.'));
  const regressed = await q(`SELECT body FROM project_doc WHERE project_id=$1`, [projId]);
  ok(String(regressed[0].body).includes(FALSE_CLAIM) && String(regressed[0].body).trim() !== COMMITTED,
     'and the EXACT historical regression — the false containment claim back in the row — is caught twice: '
     + 'by the equality check and by its own named assertion');
} finally {
  if (projId) {
    await q(`DELETE FROM project_doc WHERE project_id=$1`, [projId]).catch(() => {});
    await q(`DELETE FROM project WHERE id=$1`, [projId]).catch(() => {});
  }
  await pool.end().catch(() => {});
}
console.log(`\n${failures === 0 ? 'ALL PASSED ✓' : `${failures} FAILURE(S) ✗`}`);
process.exit(failures === 0 ? 0 : 1);
