// TICKET #15, THE OTHER HALF — a fixed projection RULE must reach the xells that already exist.
//
// `.zeehive.env` is a FILE, written from the meta-DB once, at provision time (lib/provision.js
// emitXellEnv). Ticket #15 fixed WHAT that projection computes — a xell holding production
// read-only gets the minted read-only DSN and the PROD environment, not its own throwaway spinoff
// db and dev vars — and the fix was inert for every xell provisioned before it: nothing re-emits,
// so the binding said production and the file kept saying spinoff, forever, until a human
// remembered to re-bind by hand. Nothing told them. (The zee that wrote this was one of them.)
//
// So: lib/provision.reconcileXellEnvs() — a boot-time sweep of every non-retired xell, wired in
// server/src/index.js beside the other boot reconciles. What this test pins is not "it writes a
// file"; it is the four properties that make a queenzee reaching into live worktrees acceptable:
//
//   1. STALE CORRECTS ITSELF — the manager shape (prod-readonly + an owned spinoff db) AND the
//      ordinary spinoff, with no human in the loop, to exactly what emitXellEnv would write.
//   2. IDENTICAL IS A NO-OP — a projection equal to the file on disk is not a write. A queenzee
//      that rewrites unchanged files under working zees is indistinguishable from the zee itself
//      having done it (the rule reinjectHarnessIntoLiveXells earned), and mtime is the proof.
//   3. A REWRITE UNDER A LIVE ZEE IS LOGGED, saying who wrote it.
//   4. A FAILURE IS SURFACED, NEVER SWALLOWED — the §6.2 meta-DB refusal here — as a log line, in
//      the sweep's own result, and on the xell row (env_projection_error, migration 078) so it
//      outlives the log. It clears itself once the cause is gone.
//
//   5. IT OBEYS PROVISION_MODE. A xell's database is a CLONE of the meta-DB, so the fleet rows a
//      NESTED queenzee (every zee running the server inside its own xell, PROVISION_MODE=simulate
//      by manifest default) walks are the REAL fleet's rows, worktree paths and all. Unguarded, the
//      first zee to run this would have reconciled every other zee's .zeehive.env from a snapshot.
//      In simulate it REPORTS what is stale and writes nothing.
//
// …plus: retired xells are left alone, and the two `.catch()` swallows in lib/manager-spawn.js
// (bind/unbind) are gone, because that is where this class of bug hid.
import { mkdtempSync, rmSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';

const url = process.env.DATABASE_URL;
if (!url) { console.error('DATABASE_URL required'); process.exit(2); }
process.env.PROVISION_MODE = 'simulate';
process.env.BUILD_MODE = 'simulate';

let fail = 0;
const ok = (c, m) => { console.log(`  ${c ? '✓' : '✗ FAIL'} ${m}`); if (!c) fail++; };

const { q, one, pool } = await import('../server/src/db/pool.js');
const { config } = await import('../server/src/config.js');
const { emitXellEnv, reconcileXellEnvs } = await import('../server/src/lib/provision.js');
const { recentLogs } = await import('../server/src/lib/logbus.js');

const tag = randomUUID().slice(0, 8).replace(/[^a-z0-9]/g, '');
const root = mkdtempSync(join(tmpdir(), `envrec-${tag}-`));
const RO_DSN = `postgresql://zee_ro_${tag}:pw@prod-host:5432/proddb`;
const OWNED = (n) => `postgresql://zeehive@envrec_${tag}_${n}_db:5432/zeehive`;
const envFile = (x) => join(x.wt, '.zeehive.env');
const read = (x) => readFileSync(envFile(x), 'utf8');
const varsOf = (text) => Object.fromEntries(text.split('\n')
  .map((l) => /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(l)).filter(Boolean).map((m) => [m[1], m[2]]));
const since = () => recentLogs(600).length;
const envLogsSince = (n) => recentLogs(600).slice(n).filter((l) => l.scope === 'env').map((l) => l.msg);

// the file a xell provisioned BEFORE the fix is carrying: its own spinoff db + the dev environment
const STALE = (n) => [
  '# .zeehive.env — GENERATED by ZEEHIVE from the meta-DB. Do not edit; regenerate via the console.',
  `SPINOFF_SLUG=envrec-${tag}-${n}`,
  `DATABASE_URL=${OWNED(n)}`,
  'WHICH_ENV=dev',
  '',
].join('\n');

let pid = null;

try {
  pid = (await one(
    `INSERT INTO project (name, repo_root, db_user, db_name) VALUES ($1,$2,'zeehive','zeehive') RETURNING id`,
    [`envrec-${tag}`, process.cwd()])).id;
  const xoid = (await one(`INSERT INTO xource (project_id, ref) VALUES ($1,'master') RETURNING id`, [pid])).id;

  const mkEnv = async (key, tier, vars) => {
    const e = await one(
      `INSERT INTO environment (project_id,key,tier,label,is_default) VALUES ($1,$2,$3,$4,true) RETURNING *`,
      [pid, key, tier, `${tier} (env-reconcile fixture)`]);
    for (const [name, value] of Object.entries(vars)) {
      await q(`INSERT INTO environment_var (environment_id,name,value,is_secret) VALUES ($1,$2,$3,false)`,
              [e.id, name, value]);
    }
    return e;
  };
  await mkEnv(`dev-${tag}`, 'dev', { WHICH_ENV: 'dev', API_BASE: 'https://dev.example' });
  await mkEnv(`prod-${tag}`, 'prod', { WHICH_ENV: 'prod', API_BASE: 'https://prod.example' });

  const mkXell = async (name, { coupling, roDsn = null, ownedDb = null, status = 'working' }) => {
    const slug = `envrec-${tag}-${name}`;
    const wt = join(root, name);
    mkdirSync(wt, { recursive: true });
    const x = await one(
      `INSERT INTO xell (project_id, xource_id, slug, branch, worktree_path, status, is_pooled,
                         zee_type, db_coupling, prod_ro_dsn)
         VALUES ($1,$2,$3,$4,$5,$6,false,'worker',$7,$8) RETURNING *`,
      [pid, xoid, slug, `spinoff/${slug}`, wt, status, coupling, roDsn]);
    if (ownedDb) {
      await q(`INSERT INTO container (project_id, role, tier, isolation, name, docker_ctx, internal_port,
                                      conn_ref, owner_xell_id)
                 VALUES ($1,'db','spinoff','per-xell',$2,'default',5432,$3,$4)`,
              [pid, `envrec_${tag}_${name}_db`, ownedDb, x.id]);
    }
    writeFileSync(join(wt, '.zeehive.env'), STALE(name));   // every fixture starts STALE on disk
    return { ...x, wt, name };
  };

  // the manager shape: a pooled spinoff (owned db and all) THEN bound to production read-only
  const mgr = await mkXell('mgr', { coupling: 'db-prod-readonly', roDsn: RO_DSN, ownedDb: OWNED('mgr') });
  // an ordinary spinoff — its file is stale in the boring way (missing ports/site lines)
  const spin = await mkXell('spin', { coupling: 'db-isolated', ownedDb: OWNED('spin') });
  // a xell whose DATABASE_URL resolves to the managing instance's own meta-DB: §6.2 REFUSES it
  const meta = await mkXell('meta', { coupling: 'db-isolated', ownedDb: config.databaseUrl });
  // retired: out of the fleet, and out of the sweep
  const gone = await mkXell('gone', { coupling: 'db-isolated', ownedDb: OWNED('gone'), status: 'retired' });

  // a LIVE cxell zee in the manager xell — the sweep must say the queenzee wrote that file, not it
  await q(`INSERT INTO zee (xell_id, attach_mode, entrypoint, status, viewer_kind)
             VALUES ($1,'headless-spawn','cxell-cli','working','ssh-terminal')`, [mgr.id]);

  // ── 1. a stale projection corrects itself ───────────────────────────────────────────────────
  console.log('reconcileXellEnvs: a stale .zeehive.env catches up to the meta-DB, with no human');
  const mark = since();

  // SIMULATE first — the mode every nested queenzee runs in. It must SEE the drift and touch nothing.
  const dry = await reconcileXellEnvs({ reason: 'test-simulate', mode: 'simulate' });
  ok(dry.dry_run && dry.stale.includes(mgr.slug),
     'PROVISION_MODE=simulate: the sweep still reports the stale xells it found');
  ok(read(mgr) === STALE('mgr') && read(spin) === STALE('spin'),
     'PROVISION_MODE=simulate: …and writes NOTHING — a nested queenzee walks the REAL fleet\'s rows');

  const r1 = await reconcileXellEnvs({ reason: 'test', mode: 'real' });

  const mgrVars = varsOf(read(mgr));
  ok(mgrVars.DATABASE_URL === RO_DSN,
     `manager (db-prod-readonly + owned db): DATABASE_URL is now the minted read-only DSN [${mgrVars.DATABASE_URL}]`);
  ok(mgrVars.WHICH_ENV === 'prod',
     `manager: the PROD environment's vars replaced the dev ones (WHICH_ENV=${mgrVars.WHICH_ENV})`);
  ok(mgrVars.API_BASE === 'https://prod.example', 'manager: API_BASE is production, which is ticket #15');
  const spinVars = varsOf(read(spin));
  ok(spinVars.DATABASE_URL === OWNED('spin') && spinVars.WHICH_ENV === 'dev',
     `ordinary spinoff: its own db + the dev environment [${spinVars.DATABASE_URL}]`);
  ok(spinVars.SPINOFF_SLUG === spin.slug && 'ZEEHIVE_SITE' in spinVars,
     'the whole projection is rewritten (slug/site/ports), not just DATABASE_URL');
  ok(r1.stale.includes(mgr.slug) && r1.stale.includes(spin.slug),
     `the sweep reports which files it rewrote [${r1.stale.filter((s) => s.includes(tag)).join(', ')}]`);

  // …and what it wrote is EXACTLY what emitXellEnv would write: a fresh emit finds nothing to do.
  const reEmit = await emitXellEnv(mgr.id);
  ok(reEmit.changed === false, 'the reconciled file already matches what emitXellEnv itself would write');

  // ── 2. an identical projection is a NO-OP, not a write ──────────────────────────────────────
  console.log('an unchanged projection is not written (a live zee must not see its file touched)');
  const mtimeBefore = statSync(envFile(mgr)).mtimeMs;
  const textBefore = read(mgr);
  await new Promise((res) => setTimeout(res, 12));   // ensure a rewrite would move mtime
  const r2 = await reconcileXellEnvs({ reason: 'test-again', mode: 'real' });
  ok(!r2.stale.includes(mgr.slug) && !r2.stale.includes(spin.slug),
     'the second sweep rewrites nothing — the fleet is already in sync');
  ok(statSync(envFile(mgr)).mtimeMs === mtimeBefore,
     'the file was not even touched (mtime unchanged), let alone rewritten');
  ok(read(mgr) === textBefore, 'and its contents are byte-identical');

  // ── 3. a rewrite UNDER A LIVE ZEE is logged as the queenzee's doing ──────────────────────────
  console.log('writing into a live zee\'s worktree is logged');
  const logs = envLogsSince(mark);
  // the REAL-mode line (the simulate pass logged a report-only one first)
  const mgrLine = logs.filter((m) => m.startsWith(`${mgr.slug}:`) && !/NOT rewritten/.test(m)).pop();
  ok(/STALE — rewritten/.test(mgrLine || ''), `the rewrite is logged [${(mgrLine || '(none)').slice(0, 60)}…]`);
  ok(/WHILE A ZEE IS WORKING|QUEENZEE wrote/.test(mgrLine || ''),
     'the log says a zee is working in it and that the QUEENZEE wrote the file');
  const spinLine = logs.filter((m) => m.startsWith(`${spin.slug}:`) && !/NOT rewritten/.test(m)).pop();
  ok(spinLine && !/WHILE A ZEE IS WORKING/.test(spinLine),
     'a xell with no live zee gets the plain line, not the live-zee warning');
  ok(logs.some((m) => /reconcile \(test\):.*checked.*rewritten.*FAILED/.test(m)),
     'every sweep ends in ONE summary line — "ran and found nothing" must not look like "never ran"');

  // ── 4. a failure is SURFACED — log, result, and the xell row ────────────────────────────────
  console.log('a refused/failed projection is loud, and outlives the log line');
  ok(r1.failed >= 1 && r1.broken.some((b) => b.startsWith(meta.slug)),
     `the sweep reports the failure in its result [${r1.broken.find((b) => b.startsWith(meta.slug)) || 'none'}]`);
  ok(logs.some((m) => m.startsWith(`${meta.slug}:`) && /could NOT be reconciled/.test(m)),
     'the failure is a queenzee log line naming the xell');
  const metaRow = await one(`SELECT env_projected_at, env_projection_error FROM xell WHERE id=$1`, [meta.id]);
  ok(/REFUSING to emit/.test(metaRow.env_projection_error || ''),
     `the xell row carries WHY it failed [${(metaRow.env_projection_error || 'null').slice(0, 40)}…]`);
  ok(metaRow.env_projected_at === null, 'and it is not stamped as projected — because it was not');
  ok(varsOf(read(meta)).DATABASE_URL === OWNED('meta'),
     'a refused projection leaves the old file exactly as it was (no half-written env)');

  const mgrRow = await one(`SELECT env_projected_at, env_projection_error FROM xell WHERE id=$1`, [mgr.id]);
  ok(mgrRow.env_projection_error === null && mgrRow.env_projected_at !== null,
     'a healthy xell is stamped projected, with no error');

  // the error clears itself once the cause is gone — a stale "broken" badge is its own bug
  await q(`UPDATE container SET conn_ref=$2 WHERE owner_xell_id=$1 AND role='db'`, [meta.id, OWNED('meta')]);
  const r3 = await reconcileXellEnvs({ reason: 'test-fixed', mode: 'real' });
  const metaFixed = await one(`SELECT env_projected_at, env_projection_error FROM xell WHERE id=$1`, [meta.id]);
  ok(!r3.broken.some((b) => b.startsWith(meta.slug)) && metaFixed.env_projection_error === null
     && metaFixed.env_projected_at !== null,
     'once the cause is fixed the next sweep clears the error and stamps the projection');

  // ── 5. retired xells are not touched ────────────────────────────────────────────────────────
  ok(read(gone) === STALE('gone'),
     'a RETIRED xell is left alone — the sweep is the live fleet, not an archive rewrite');

  // ── 6. the wiring, and the swallows that hid this class of bug ──────────────────────────────
  console.log('boot wiring + no swallowed .catch()');
  const boot = readFileSync('server/src/index.js', 'utf8');
  ok(/reconcileXellEnvs\(/.test(boot), 'the sweep is wired into the queenzee boot (server/src/index.js)');
  const ms = readFileSync('server/src/lib/manager-spawn.js', 'utf8');
  ok(!/emitXellEnv\([^)]*\)\.catch\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)/.test(ms),
     'manager-spawn no longer swallows a failed re-emit in an empty .catch()');
  ok(/console\.error\(`\[prod-ro\][^`]*\.zeehive\.env/.test(ms),
     'a bind/unbind that cannot re-emit says so on stdout as well as the queenzee log');

  console.log(fail ? `\n${fail} FAILED` : '\nall good');
} catch (e) {
  console.error('TEST ERROR:', e);
  fail++;
} finally {
  if (pid) await q(`DELETE FROM project WHERE id=$1`, [pid]).catch(() => {});
  await pool.end().catch(() => {});
  try { rmSync(root, { recursive: true, force: true }); } catch { /* */ }
}
process.exit(fail ? 1 : 0);
