// GENERATED spinoff compose — ZEEHIVE authors a project's per-xell compose file as a PROJECTION
// of its manifest (docs/compose-authorship-decision-record.md). Three rules govern this module:
//
//   1. MACHINE FACTS STAY OUT. No docker context, host IP or site name ever appears in the
//      output — placement lives in the meta-DB (machine/machine_pool) and the SAME generated
//      file runs on any daemon via `docker --context` (that is what makes a spin stack land on
//      whatever machine the pool chose). A compose file with a machine name in it would be
//      house rule 7 broken in a new place.
//   2. STANDALONE-WORKABLE. Every parameter interpolates with a default
//      (`${SPINOFF_SERVER_PORT:-4800}`), so a human with no harness at all can run
//      `SPINOFF_SLUG=demo docker compose -f docker-compose.spinoff.yml up` and get a working
//      stack. ZEEHIVE passes the real values (build-container.sh env contract: SPINOFF_SLUG,
//      SPINOFF_SERVER_PORT, SPINOFF_WEB_PORT, SPINOFF_DB_PORT, -p <compose_project>).
//   3. OWNERSHIP IS THE MARKER. A file whose first line carries GENERATED_MARKER is ZEEHIVE's
//      to regenerate freely; ANY other compose file is the project's own (onboarded — spec
//      §3.1 compose onboarding) and writeGeneratedCompose REFUSES to touch it. The marker is
//      in the file, not a DB flag, so ownership survives clones and reads the same on every
//      surface.
//
// Service names are the ROLE names (server/webapp/db) — that is the contract
// scripts/build-container.sh drives (`case "$ROLE" in server) SVC=server;;`); the manifest's
// roles.<r>.service mapping describes a project's OWN (onboarded) compose files, not this one.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify } from 'yaml';
import { sanitizeName, defaultNaming } from './manifest.js';

export const GENERATED_MARKER = '# GENERATED by ZEEHIVE';
const MARKER_RE = /^#\s*GENERATED by ZEEHIVE/;

// Is this compose text ZEEHIVE's to regenerate? First non-empty line carries the marker.
export function isGeneratedCompose(text) {
  const first = String(text || '').split('\n').find((l) => l.trim() !== '') || '';
  return MARKER_RE.test(first);
}

// Fill a naming template with the compose-interpolation form of the slug, so the generated file
// derives per-xell names the same way namingFor does at provision — one formula, two worlds.
const slugVar = '${SPINOFF_SLUG:-dev}';
function nameFor(project, section, role) {
  const naming = { ...defaultNaming(project?.name)[section], ...(project?.manifest?.naming?.[section] || {}) };
  return String(naming[role] || naming.default)
    .replaceAll('{project}', sanitizeName(project?.name))
    .replaceAll('{role}', role)
    .replaceAll('{slug}', slugVar);
}

const INTERNAL_DEFAULTS = { server: 3000, webapp: 5173, db: 5432 };
const PORT_VAR = { server: 'SPINOFF_SERVER_PORT', webapp: 'SPINOFF_WEB_PORT', db: 'SPINOFF_DB_PORT' };

// Generate the spinoff compose OBJECT + YAML for a project row ({ name, manifest }).
// Throws with a named reason when the manifest lacks what generation needs — a buildable role
// without a dockerfile is a config gap to fix in zeehive.yml, not something to guess.
export function generateSpinoffCompose(project) {
  const m = project?.manifest || {};
  const spin = m.tiers?.spinoff || {};
  const roles = m.roles || {};
  const p = sanitizeName(project?.name);
  const dbRole = roles.db && roles.db.service ? 'db' : null;
  const mdb = m.db || {};
  const dbUser = mdb.user || 'postgres';
  const dbPass = mdb.password || 'dev';
  const dbName = mdb.name || 'app';

  const portOf = (role) => {
    const decl = spin.ports?.[role] || {};
    const internal = Number(decl.internal) || INTERNAL_DEFAULTS[role];
    const base = Number(decl.base) || null;
    return { internal, published: base ? `\${${PORT_VAR[role]}:-${base}}` : null };
  };
  const labels = (role) => ({
    'zeehive.project': project?.name || p, 'zeehive.role': role, 'zeehive.slug': slugVar,
  });

  const services = {};
  const missing = [];
  for (const role of ['server', 'webapp']) {
    const r = roles[role];
    if (!r) continue;
    if (r.buildable === false) continue;
    if (!r.dockerfile) { missing.push(`roles.${role}.dockerfile`); continue; }
    const { internal, published } = portOf(role);
    const svc = {
      build: {
        context: '.',
        dockerfile: r.dockerfile,
        ...(r.build_args && Object.keys(r.build_args).length ? { args: { ...r.build_args } } : {}),
      },
      image: nameFor(project, 'image', role),
      container_name: nameFor(project, 'container', role),
      restart: 'unless-stopped',
      ...(published ? { ports: [`${published}:${internal}`] } : {}),
      labels: labels(role),
    };
    if (role === 'server') {
      svc.environment = {
        PORT: String(internal),
        ...(dbRole ? { DATABASE_URL: `postgresql://${dbUser}:${dbPass}@db:5432/${dbName}` } : {}),
        // The tier's declared env rides INSIDE the generated file (not only in .zeehive.env):
        // for Zeehive that is the §6.2 simulate-safety set, and baking it here means a nested
        // queenzee is safe even when someone runs this compose entirely outside the harness.
        ...Object.fromEntries(Object.entries(spin.env || {}).map(([k, v]) => [k, String(v)])),
      };
      if (dbRole) svc.depends_on = { db: { condition: 'service_healthy' } };
    }
    services[role] = svc;
  }
  if (missing.length) {
    throw new Error(`cannot generate a spinoff compose: ${missing.join(', ')} not declared in zeehive.yml`);
  }
  if (!Object.keys(services).length) {
    throw new Error('cannot generate a spinoff compose: no buildable server/webapp roles in the manifest');
  }

  if (dbRole) {
    const { internal, published } = portOf('db');
    services.db = {
      image: roles.db.image || 'postgres:17-alpine',
      container_name: nameFor(project, 'container', 'db'),
      restart: 'unless-stopped',
      ...(published ? { ports: [`${published}:${internal}`] } : {}),
      environment: { POSTGRES_USER: dbUser, POSTGRES_PASSWORD: dbPass, POSTGRES_DB: dbName },
      healthcheck: {
        test: ['CMD-SHELL', `pg_isready -U ${dbUser}`],
        interval: '5s', timeout: '3s', retries: 20,
      },
      // Deliberately NO volume: a per-xell db is a throwaway — its data dies with the stack,
      // which is exactly the isolation the db-isolated coupling promises.
      labels: labels('db'),
    };
  }

  // ── the MESH SIDECAR (docs/netbird-mesh-plan.md §3.3) — manifest OPT-IN (tiers.spinoff.mesh) ──
  // The xell's network identity: a NetBird agent joins the mesh as peer `<slug>` and DNATs the
  // CANONICAL role ports (the same `internal` values above) one hop to the role services, so
  // `<slug>.<mesh-domain>:5432/:<server>/:<webapp>` reaches this stack on ANY machine with no
  // published host ports. Rules 1–2 hold: no machine facts (the management URL and the per-xell
  // setup key are interpolations the provisioner supplies), and the file stays standalone-workable
  // — with no setup key the sidecar SAYS SO and idles, so `docker compose up` without the harness
  // still brings the stack up exactly as before. NB_SETUP_KEY/NB_MANAGEMENT_URL/NB_HOSTNAME are
  // read by the netbird binary itself; the wrapper execs the image's own entrypoint
  // (/usr/local/bin/netbird-entrypoint.sh — verified against netbirdio/netbird client/Dockerfile).
  const mesh = spin.mesh || {};
  if (mesh.enabled) {
    const forwards = ['server', 'webapp', 'db']
      .filter((role) => services[role])
      .map((role) => `${role}:${portOf(role).internal}`)
      .join(' ');
    // Shell vars are $$-escaped (compose folds $$ to $); plain strings, because a JS template
    // literal would try to interpolate the shell's own ${…} forms.
    const run = [
      'if [ -z "$$NB_SETUP_KEY" ]; then echo \'mesh sidecar idle: no SPINOFF_MESH_SETUP_KEY (mesh disabled for this xell)\'; exec sleep infinity; fi',
      'for t in ' + forwards + '; do s=$${t%%:*}; p=$${t##*:}; ip=$$(getent hosts "$$s" | awk \'{print $$1}\' | head -1); if [ -n "$$ip" ]; then'
        + ' iptables -t nat -A PREROUTING -p tcp --dport "$$p" -j DNAT --to-destination "$$ip:$$p";'
        + ' iptables -t nat -A POSTROUTING -d "$$ip" -p tcp --dport "$$p" -j MASQUERADE;'
        + ' else echo "mesh sidecar: no address for $$s — not forwarding :$$p"; fi; done',
      'exec /usr/local/bin/netbird-entrypoint.sh',
    ].join('\n');
    services.mesh = {
      image: mesh.image || 'netbirdio/netbird:latest',
      container_name: nameFor(project, 'container', 'mesh'),
      hostname: slugVar,
      restart: 'unless-stopped',
      cap_add: ['NET_ADMIN'],
      devices: ['/dev/net/tun:/dev/net/tun'],
      environment: {
        NB_SETUP_KEY: '${SPINOFF_MESH_SETUP_KEY:-}',
        NB_MANAGEMENT_URL: '${SPINOFF_MESH_MGMT_URL:-}',
        NB_HOSTNAME: slugVar,
      },
      entrypoint: ['/bin/sh', '-c', run],
      labels: labels('mesh'),
    };
  }

  const header = `${GENERATED_MARKER} from zeehive.yml — do not hand-edit; regenerate via the console
# (Project setup → Manifest) or POST /api/projects/:id/compose/generate. A compose file WITHOUT
# this marker is the project's own and ZEEHIVE will never overwrite it.
#
# Standalone (no harness): SPINOFF_SLUG=demo docker compose -f <this file> up
# Under ZEEHIVE: build-container.sh drives it with -p <project> and the SPINOFF_* env.
# No machine facts in here, by design — the same file runs on any daemon via docker --context;
# WHERE a stack runs is meta-DB data (machine/machine_pool), never file content.
`;
  return { yaml: header + stringify({ services }), services };
}

// Write the generated compose into the project repo — ONLY over a file ZEEHIVE generated (or no
// file at all). A project-owned compose (no marker) is never touched: that is the onboarding
// boundary, and the refusal names it.
export function writeGeneratedCompose(repoRoot, file, yaml) {
  const path = resolve(String(repoRoot || '').replace(/\\/g, '/'), file);
  if (existsSync(path)) {
    const current = readFileSync(path, 'utf8');
    if (!isGeneratedCompose(current)) {
      return { ok: false, wrote: false, path, refused: true,
               reason: `${file} exists and is not ZEEHIVE-generated (no marker) — it is the project's own compose; onboard it instead of overwriting it` };
    }
    if (current === yaml) return { ok: true, wrote: false, path, unchanged: true };
  }
  writeFileSync(path, yaml);
  return { ok: true, wrote: true, path };
}
