// Deterministic xell provisioning. Materializes a xell + its container stack in the
// meta-DB. In 'real' mode it also runs scripts/provision-xell.sh (git worktree +
// spin-env up on ugreen-nas); in 'simulate' mode it only records the modeled state
// (correctly-computed ports/names) with NO live side effects on the dev NAS.
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { pool, q, one } from '../db/pool.js';
import { config } from '../config.js';
import { broadcast } from '../lib/events.js';
import { headCommit, cleanGitEnv } from './git.js';
import { resolveSite } from './sites.js';
import { namingFor } from './manifest.js';
import { resolveBash } from './bash.js';

const ADJ = ['swift', 'calm', 'bright', 'bold', 'keen', 'lively', 'nimble', 'quiet', 'sunny', 'wise'];
const NOUN = ['harbor', 'meadow', 'summit', 'delta', 'ember', 'grove', 'atlas', 'cove', 'ridge', 'vale'];

// Mirror of spin-env.sh: slot = (first 4 hex of md5(slug)) % slot_mod. Bases/mod come from the
// project row (port_server_base/port_web_base/port_slot_mod); the numeric defaults keep the
// OmniBiz-era values for callers that don't pass a project.
export function computePorts(slug, project = {}) {
  const mod = Number(project.port_slot_mod) || 90;
  const hex = crypto.createHash('md5').update(slug).digest('hex').slice(0, 4);
  const slot = parseInt(hex, 16) % mod;
  return {
    slot,
    serverPort: (Number(project.port_server_base) || 3100) + slot,
    webPort: (Number(project.port_web_base) || 5200) + slot,
  };
}

// The harness-free projection (spec §3.4): a generated, gitignored env file in the worktree so
// `docker compose --env-file .env --env-file .zeehive.env -f <spinoff compose> up` works with
// ZEEHIVE stopped. Parameters ONLY — never secrets (those stay in the main checkout's .env).
// Pure projection of meta-DB truth: regenerable at any time, meaningless to hand-edit.
// Two postgres URLs meaning the same database? Compared on host:port+dbname, not string equality
// — localhost spellings differ but the port+db pair is what actually collides.
function sameDatabase(a, b) {
  const parse = (s) => { try { return new URL(String(s).replace(/^postgres(ql)?:/, 'http:')); } catch { return null; } };
  const ua = parse(a), ub = parse(b);
  if (!ua || !ub) return String(a) === String(b);
  const host = (u) => (['localhost', '127.0.0.1', '::1'].includes(u.hostname) ? 'localhost' : u.hostname);
  return host(ua) === host(ub) && ua.port === ub.port && ua.pathname === ub.pathname;
}

export async function emitXellEnv(xellId) {
  const xell = await one(`SELECT * FROM xell WHERE id=$1`, [xellId]);
  if (!xell?.worktree_path) throw new Error('xell has no worktree');
  if (!existsSync(xell.worktree_path)) throw new Error(`worktree does not exist: ${xell.worktree_path}`);
  const project = await one(`SELECT * FROM project WHERE id=$1`, [xell.project_id]);
  const site = await resolveSite(xell.project_id, 'dev');
  const cs = await q(
    `SELECT role, host_port, conn_ref FROM container
      WHERE owner_xell_id=$1 AND role IN ('server','webapp','db')`, [xellId]);
  const portOf = (role) => cs.find((c) => c.role === role)?.host_port ?? '';

  const spin = project?.manifest?.tiers?.spinoff || {};
  const serverEnv = spin.ports?.server?.env || 'SPINOFF_SERVER_PORT';
  const webEnv = spin.ports?.webapp?.env || 'SPINOFF_WEB_PORT';
  const lines = [
    '# .zeehive.env — GENERATED by ZEEHIVE from the meta-DB. Do not edit; regenerate via the console.',
    `SPINOFF_SLUG=${xell.slug}`,
    `${serverEnv}=${portOf('server')}`,
    `${webEnv}=${portOf('webapp')}`,
    `ZEEHIVE_SITE=${site?.key || 'dev'}`,
    `ZEEHIVE_DOCKER_CONTEXT=${site?.docker_ctx || config.dockerCtx}`,
  ];

  // The xell's OWN database, when it has one. HARD GUARD (spec §6.2): never emit the managing
  // instance's meta-DB — two queenzees reconciling one meta-DB reap each other's xells; that
  // failure class has destroyed live work before, so it is a refusal, not a warning.
  let dbUrl = cs.find((c) => c.role === 'db')?.conn_ref || null;
  // db-clone: no owned db container, but its OWN database (db_instance row) inside the shared
  // dev postgres — the shared container's conn_ref with the database name swapped for the
  // clone's. The bare conn_ref must never be emitted for a clone xell: it names the SHARED db.
  if (!dbUrl && xell.db_coupling === 'db-clone') {
    const inst = await one(
      `SELECT di.name, c.conn_ref FROM db_instance di JOIN container c ON c.id = di.container_id
        WHERE di.owner_xell_id=$1 AND di.kind='clone' AND c.conn_ref IS NOT NULL LIMIT 1`, [xellId]);
    if (inst?.conn_ref) {
      try {
        const u = new URL(String(inst.conn_ref).replace(/^postgres(ql)?:/, 'http:'));
        u.pathname = `/${inst.name}`;
        dbUrl = String(u).replace(/^http:/, 'postgresql:');
      } catch { /* unparseable conn_ref — emit nothing rather than the shared db */ }
    }
  }
  if (dbUrl) {
    if (sameDatabase(dbUrl, config.databaseUrl)) {
      throw new Error(`REFUSING to emit .zeehive.env: the xell's DATABASE_URL resolves to the `
        + `managing instance's own meta-DB (${config.databaseUrl.replace(/:[^:@/]+@/, ':***@')}) — `
        + 'a nested queenzee on the real meta-DB reaps live xells. Re-point the xell db first.');
    }
    lines.push(`DATABASE_URL=${dbUrl}`);
  }

  // Manifest-declared extra env for spinoffs — for Zeehive itself these are the §6.2 safety
  // defaults (BUILD_MODE=simulate, POOL_TARGET_READY=0, …) that keep a nested queenzee inert.
  for (const [k, v] of Object.entries(spin.env || {})) lines.push(`${k}=${v}`);
  lines.push('');

  const wt = xell.worktree_path.replace(/\\/g, '/');
  const path = `${wt}/.zeehive.env`;
  writeFileSync(path, lines.join('\n'));

  // Keep the projection out of git's sight WITHOUT touching the project's committed .gitignore:
  // the repo-local exclude file (info/exclude, shared across this repo's worktrees) exists for
  // exactly this class of machine-local artifact. Skipping this made land-xell.sh count every
  // fresh xell as dirty and the pool decommissioned them in a loop (2026-07-17). Best-effort —
  // land-xell.sh also excludes it explicitly as defense in depth.
  try {
    const r = spawnSync('git', ['-C', wt, 'rev-parse', '--path-format=absolute', '--git-path', 'info/exclude'],
      { encoding: 'utf8', timeout: 10000, windowsHide: true });
    const excl = r.status === 0 ? r.stdout.trim() : null;
    if (excl) {
      const cur = existsSync(excl) ? readFileSync(excl, 'utf8') : '';
      if (!cur.split(/\r?\n/).includes('.zeehive.env')) {
        mkdirSync(dirname(excl), { recursive: true });
        writeFileSync(excl, `${cur}${cur && !cur.endsWith('\n') ? '\n' : ''}.zeehive.env\n`);
      }
    }
  } catch { /* exclusion is a nicety; the projection itself matters more */ }
  return { ok: true, path, slug: xell.slug };
}

// ── bootstrap prerequisites (spec §4.2/§4.3) ──────────────────────────────────
// The manifest's `tiers.spinoff.requires` names the external networks/volumes a spinoff needs
// BEFORE it can come up. Verified here so a missing prerequisite is a clear one-line bootstrap
// error at provision time instead of a crash-loop discovered from container logs. Network entries
// may be strings or {name, aliases:[...]}; a declared alias that resolves to nothing is the known
// "db recreated by docker run drops the compose alias → the whole fleet crash-loops" failure, so
// it fails provision loudly. Volumes are DATA — verified, NEVER auto-created.
export function verifyRequires(ctx, requires = {}) {
  const dk = (args) => spawnSync('docker', ['--context', ctx, ...args],
    { encoding: 'utf8', timeout: 20000, windowsHide: true });
  const nets = (requires.networks || []).map((n) =>
    typeof n === 'string' ? { name: n, aliases: [] } : { name: n.name, aliases: n.aliases || [] });
  for (const n of nets) {
    const r = dk(['network', 'inspect', n.name, '--format',
      '{{range $id, $c := .Containers}}{{$c.Name}} {{end}}']);
    if (r.status !== 0) {
      throw new Error(`required network "${n.name}" does not exist on ${ctx} — bring up the `
        + `canonical dev stack first (it creates it); see the project's bootstrap doc`);
    }
    if (n.aliases.length) {
      const attached = (r.stdout || '').trim().split(/\s+/).filter(Boolean);
      const found = new Set();
      if (attached.length) {
        const ins = dk(['inspect', ...attached, '--format',
          `{{json (index .NetworkSettings.Networks "${n.name}").Aliases}}`]);
        for (const line of (ins.stdout || '').split('\n')) {
          try { for (const a of JSON.parse(line) || []) found.add(a); } catch { /* null/garbage line */ }
        }
      }
      const missing = n.aliases.filter((a) => !found.has(a));
      if (missing.length) {
        throw new Error(`network "${n.name}" on ${ctx} is missing required alias(es): `
          + `${missing.join(', ')} — a container was recreated without them (a bare docker run `
          + `drops compose aliases); re-create it via compose before provisioning`);
      }
    }
  }
  for (const v of requires.volumes || []) {
    const r = dk(['volume', 'inspect', v]);
    if (r.status !== 0) {
      throw new Error(`required external volume "${v}" does not exist on ${ctx} — it is DATA and `
        + `is never auto-created; see the project's bootstrap doc`);
    }
  }
  return { ok: true };
}

export async function makeSlug(projectId) {
  for (let i = 0; i < 50; i++) {
    const a = ADJ[crypto.randomInt(ADJ.length)];
    const n = NOUN[crypto.randomInt(NOUN.length)];
    const suffix = crypto.randomBytes(3).toString('hex');
    const slug = `${a}-${n}-${suffix}`;
    const clash = await one(`SELECT 1 FROM xell WHERE project_id=$1 AND slug=$2`, [projectId, slug]);
    if (!clash) return slug;
  }
  throw new Error('could not allocate a unique slug');
}

// Provision one pooled (empty, ready) xell for a project.
export async function provisionXell({ projectId, mode = 'simulate', sourceCoupling, dbCoupling }) {
  const project = await one(`SELECT * FROM project WHERE id=$1`, [projectId]);
  const xource = await one(`SELECT * FROM xource WHERE project_id=$1 AND ref=$2`, [projectId, project.main_branch]);
  const cfg = await one(`SELECT * FROM pool_config WHERE project_id=$1`, [projectId]);
  const slug = await makeSlug(projectId);
  const branch = `spinoff/${slug}`;
  const worktree = `${project.repo_root.replace(/\\/g, '/')}/.claude/worktrees/${slug}`;
  const ports = computePorts(slug, project);

  // WHERE this xell's app tier runs: the project's default dev site (falls back to the
  // deprecated project columns, then the global env default — see lib/sites.js).
  const devSite = await resolveSite(projectId, 'dev');
  const devCtx = devSite?.docker_ctx || config.dockerCtx;
  const devHost = devSite?.host || project.dev_host_ip || config.devHostIp;
  const devSiteId = devSite?.id || null;
  const url = `http://${devHost}:${ports.webPort}`;

  // the xell branches off the CURRENT xource tip — capture it (cheap, both modes)
  let head = headCommit(project.repo_root, project.main_branch);
  let health = 'unknown';
  if (mode === 'real') {
    // PROVISION_APP_TIER=false → create only the isolated worktree (no spin-env / NAS
    // containers). A gentle on-ramp: code isolation now, app tier when you want it.
    const appTier = process.env.PROVISION_APP_TIER !== 'false';
    // manifest-declared bootstrap prerequisites fail FAST with a named step, not a crash-loop
    const requires = project.manifest?.tiers?.spinoff?.requires;
    if (appTier && requires) verifyRequires(devCtx, requires);
    const script = resolve(config.repoRoot, 'scripts', 'provision-xell.sh');
    // Pass the project's source branch — the script used to hardcode 'main', which silently
    // ignored main_branch and broke every project that isn't on main.
    const r = spawnSync(resolveBash(), [script, slug, project.repo_root.replace(/\\/g, '/'), project.main_branch], {
      encoding: 'utf8', timeout: 600000,
      env: cleanGitEnv({ SPINOFF_DOCKER_CONTEXT: devCtx, DEV_HOST_IP: devHost,
             PROVISION_APP_TIER: appTier ? 'true' : 'false' }),
    });
    if (r.status !== 0) throw new Error(`provision-xell.sh failed: ${(r.stderr || '').slice(-500)}`);
    health = appTier ? 'up' : 'down'; // worktree exists; containers only up if the app tier ran
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const { rows: [xell] } = await client.query(
      `INSERT INTO xell (project_id,xource_id,slug,branch,worktree_path,git_dir,head_commit,
          source_coupling,db_coupling,status,is_pooled,ready_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'ready',true,now()) RETURNING *`,
      [projectId, xource.id, slug, branch, worktree,
       `${worktree}/.git`, head,
       sourceCoupling || cfg.default_source_coupling, dbCoupling || cfg.default_db_coupling]);

    // per-xell containers: its own server + webapp
    // Names/images/compose-project come from the project's naming templates (manifest-backed,
    // defaults derived from the project name — see lib/manifest.js). Never hardcoded per project.
    // Spawn-template default for WHERE these images compile. NULL (or equal to the run context) ⇒
    // build on the run host, unchanged. A foreign value was already validated to have a registry
    // when it was set on pool_config, so a pooled xell inherits a build host that actually works.
    const defaultBuildCtx = cfg.default_build_ctx && cfg.default_build_ctx !== devCtx ? cfg.default_build_ctx : null;
    const mk = async (role, hostPort, intPort, curl) => {
      const nm = namingFor(project, role, slug);
      const { rows: [c] } = await client.query(
        `INSERT INTO container (project_id,role,tier,isolation,name,image_tag,docker_ctx,build_ctx,host,host_port,internal_port,url,compose_project,compose_file,owner_xell_id,site_id,health)
         VALUES ($1,$2,'spinoff','per-xell',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id`,
        [projectId, role, nm.container, nm.image, devCtx, defaultBuildCtx, devHost, hostPort, intPort, curl,
         nm.composeProject, project.compose_spinoff, xell.id, devSiteId, health]);
      await client.query(`INSERT INTO xell_uses_container (xell_id,container_id,relation) VALUES ($1,$2,'owns')`, [xell.id, c.id]);
    };
    await mk('server', ports.serverPort, 3000, `http://${devHost}:${ports.serverPort}`);
    await mk('webapp', ports.webPort, 5173, url);

    // db coupling: link the shared dev db it USES (db-shared-dev default). db-clone lives in the
    // SAME container — the clone database itself is cut lazily (at dispatch, or by the
    // schema-work watch), never for a pristine pooled xell.
    if (['db-shared-dev', 'db-clone'].includes(dbCoupling || cfg.default_db_coupling)) {
      const shared = await client.query(
        `SELECT id FROM container WHERE project_id=$1 AND role='db' AND tier='dev' AND isolation='shared' LIMIT 1`, [projectId]);
      if (shared.rows[0]) {
        await client.query(`INSERT INTO xell_uses_container (xell_id,container_id,relation) VALUES ($1,$2,'uses') ON CONFLICT DO NOTHING`, [xell.id, shared.rows[0].id]);
      }
    }
    await client.query('COMMIT');
    broadcast('xell', xell);
    // the harness-free projection rides every REAL provision; failure is logged, never fatal
    // (the xell works without it — the file only serves ZEEHIVE-less compose runs)
    if (mode === 'real') {
      await emitXellEnv(xell.id).catch((e) => console.error(`[provision] .zeehive.env: ${e.message}`));
    }
    return { ...xell, ports, url, mode };
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}
