// UI-driven HOST-FOLDER MOUNTS for the containerized queenzee (console → onboard → mount).
//
// A bind mount cannot be added to a running container, so "mount D:\Repos\X into /repos/X"
// necessarily means RECREATING the queenzee's own container with one more volume. That is the
// self-ship pattern (scripts/self-ship-container.sh): write the desired state down, then detach
// a sibling docker:cli container on the mounted socket to `compose up -d server` — the sibling
// outlives us, and the new container comes up with the mount.
//
// Everything the recreate needs is discoverable from THIS container's own compose labels:
// project name, config files (host paths — bindable into the sibling, since bind sources
// resolve daemon-side), and the working dir (compose reads .env there). The mounts themselves
// live in TWO files inside the repos volume, so they survive the recreate and stack up:
//   /repos/.zeehive-mounts.json — the registry (what the console lists and edits)
//   /repos/.zeehive-mounts.yml  — the generated compose override the sibling passes with -f
//
// KNOWN LIMIT, stated in the console too: a hand-run `docker compose up` on the host that omits
// the mounts file drops every UI mount (compose recreates from ITS files alone). The project
// then probes "folder does not exist" — loud, recoverable by re-mounting from the console.
import { spawnSync } from 'node:child_process';
import { hostname } from 'node:os';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { logline } from './logbus.js';

const REG = '/repos/.zeehive-mounts.json';
const YML = '/repos/.zeehive-mounts.yml';

const docker = (args, timeout = 20000) =>
  spawnSync('docker', args, { encoding: 'utf8', timeout, windowsHide: true });

// This process's own container: labels + the /repos volume name. null = not containerized
// (a host-era queenzee sees the operator's filesystem directly — nothing to mount).
function selfContainer() {
  const r = docker(['inspect', hostname()]);
  if (r.status !== 0) return null;
  let info;
  try { info = JSON.parse(r.stdout)[0]; } catch { return null; }
  const L = info?.Config?.Labels || {};
  const files = (L['com.docker.compose.project.config_files'] || '').split(',').map((s) => s.trim()).filter(Boolean);
  const reposVol = (info?.Mounts || []).find((m) => m.Type === 'volume' && m.Destination === '/repos')?.Name;
  if (!files.length || !reposVol) return null;
  return {
    project: L['com.docker.compose.project'] || 'zeehive',
    service: L['com.docker.compose.service'] || 'server',
    files,
    workingDir: L['com.docker.compose.project.working_dir'] || null,
    reposVol,
  };
}

const readReg = () => {
  try { return JSON.parse(readFileSync(REG, 'utf8')); } catch { return []; }
};

// One generated override carrying EVERY registered mount — long volume syntax on purpose:
// short "D:/x:/repos/x" strings misparse around Windows drive colons.
function writeOverride(reg, service) {
  const lines = [
    '# GENERATED by Zeehive (console -> onboard -> mount host folder). Do not edit:',
    '# regenerated on every mount/unmount; passed with -f on every self-recreate.',
  ];
  if (!reg.length) {
    // an EMPTY override must still be a valid -f argument (`volumes:` with no list is not)
    lines.push('services: {}');
  } else {
    lines.push('services:', `  ${service}:`, '    volumes:');
    for (const m of reg) {
      lines.push('      - type: bind');
      lines.push(`        source: '${m.host}'`);
      lines.push(`        target: '/repos/${m.name}'`);
    }
  }
  writeFileSync(YML, lines.join('\n') + '\n');
}

export function listHostMounts() {
  const self = selfContainer();
  return {
    containerized: !!self,
    mounts: readReg().map((m) => ({ ...m, present: existsSync(`/repos/${m.name}`) })),
  };
}

export function mountHostFolder({ host_path, name } = {}) {
  const self = selfContainer();
  if (!self) {
    throw new Error('this queenzee is not containerized — it sees the machine\'s filesystem directly, '
      + 'so onboard the folder by its real path instead of mounting it');
  }
  const host = String(host_path || '').trim().replace(/\\/g, '/').replace(/\/+$/, '');
  if (!host) throw new Error('host_path is required (a folder on the machine that runs docker)');
  const slug = String(name || host.split('/').filter(Boolean).pop() || '').trim();
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(slug)) throw new Error(`bad mount name "${slug}" — letters, digits, . _ - only`);

  const reg = readReg();
  const dupe = reg.find((m) => m.name === slug);
  if (dupe && dupe.host !== host) throw new Error(`/repos/${slug} is already mapped to ${dupe.host} — unmount it first or pick another name`);
  if (!dupe) reg.push({ name: slug, host, added_at: new Date().toISOString() });
  writeFileSync(REG, JSON.stringify(reg, null, 2));
  writeOverride(reg, self.service);

  // Sibling recreate: bind each compose file in read-only at a fixed path, the working dir for
  // .env resolution, and the repos volume for the mounts override. `up -d --no-deps <service>`
  // touches ONLY our own container — meta-db and web stay as they are.
  const args = ['run', '-d', '--rm', '-v', '/var/run/docker.sock:/var/run/docker.sock',
    '-v', `${self.reposVol}:/repos:ro`];
  const fArgs = [];
  self.files.forEach((f, i) => {
    args.push('-v', `${f}:/bs/f${i}.yml:ro`);
    fArgs.push('-f', `/bs/f${i}.yml`);
  });
  if (self.workingDir) args.push('-v', `${self.workingDir}:/pwd:ro`);
  const compose = ['docker', 'compose', '-p', self.project,
    ...(self.workingDir ? ['--project-directory', '/pwd'] : []),
    ...fArgs, '-f', YML, 'up', '-d', '--no-deps', self.service].join(' ');
  args.push('docker:cli', 'sh', '-c', `sleep 2; ${compose}`);

  const r = docker(args, 60000);
  if (r.status !== 0) throw new Error(`could not detach the recreate helper: ${(r.stderr || r.stdout || '').trim().slice(0, 300)}`);
  logline('api', `host mount requested: ${host} -> /repos/${slug} — recreating own container to take the bind (sibling ${String(r.stdout).trim().slice(0, 12)})`);
  return { ok: true, target: `/repos/${slug}`, restarting: true };
}
