// /OONEY plumbing — resolve which xell this session is, call the gate, print what it says.
//
//   xell-ooney.mjs [server|webapp|both] [--reason "..."] [--wait[=secs]] [--xell <id>]
//
// DELIBERATELY CONTAINS NO PROCEDURE. Every instruction — how to land, what schema drift means,
// when to poll, what "live" looks like — comes back from POST /api/ooney/check, generated by the
// queenzee from live state at the moment it applies. Text baked into this file (or a skill .md)
// would drift from what the gate actually enforces; the server's answer cannot.
//
// --wait polls until the verdict is 'live' or 'deny'. Run it in the BACKGROUND: its exit is your
// nudge (the harness re-invokes you when a background task finishes). Do not hand-poll.
import http from 'node:http';

const api = process.env.ZEEHIVE_API || 'http://localhost:4700';
const sid = process.env.CLAUDE_CODE_SESSION_ID || '';
const argv = process.argv.slice(2);
const waitArg = argv.find((a) => a === '--wait' || a.startsWith('--wait='));
const waitSecs = waitArg?.includes('=') ? Number(waitArg.split('=')[1]) || 3600 : 3600;
const ri = argv.indexOf('--reason');
const reason = ri >= 0 ? argv[ri + 1] : null;
const xi = argv.indexOf('--xell');
const explicit = xi >= 0 ? argv[xi + 1] : null;
const targetWord = argv.find((a) => ['server', 'webapp', 'both'].includes(a));
const targets = targetWord === 'server' ? ['server'] : targetWord === 'webapp' ? ['webapp'] : null; // null = both

const req = (method, p, obj) => new Promise((res, rej) => {
  const body = obj ? JSON.stringify(obj) : null;
  const r = http.request(`${api}${p}`, {
    method,
    headers: body ? { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body) } : {},
  }, (x) => { let b = ''; x.on('data', (c) => (b += c)); x.on('end', () => res({ code: x.statusCode, body: b })); });
  r.on('error', rej); if (body) r.write(body); r.end();
});
const json = (r) => { try { return JSON.parse(r.body); } catch { return {}; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function resolveXell() {
  if (explicit) return explicit;
  if (!sid) { console.log('No CLAUDE_CODE_SESSION_ID and no --xell — cannot tell which xell you are.'); process.exit(1); }
  const st = await req('GET', `/api/xell/status?session_id=${encodeURIComponent(sid)}`);
  if (st.code >= 400) { console.log(`No xell for this session (HTTP ${st.code}).`); process.exit(1); }
  const s = json(st);
  const id = s.xell?.id || s.xell_id;
  if (!id) { console.log('Could not resolve this session\'s xell.'); process.exit(1); }
  return id;
}

function render(v) {
  const mark = { pass: '✓', wait: '…', deny: '✗', live: '★' };
  console.log('');
  for (const s of v.steps || []) {
    console.log(`  ${mark[s.verdict] || '·'} [${s.gate}] ${s.instruction}`);
  }
  console.log(`\n  verdict: ${v.verdict.toUpperCase()}  (targets: ${(v.targets || []).join(' + ')})\n`);
}

const xellId = await resolveXell();
const check = () => req('POST', '/api/ooney/check', { xell_id: xellId, targets, reason });

// EXIT 0 WHENEVER A VERDICT WAS DELIVERED — including DENY. A deny is the gate answering, not
// this command failing, and the skill harness renders any non-zero exit as "Error: Shell command
// failed" — which dressed a correct, actionable verdict up as a crash (seen live: a zee's deny
// for 2 uncommitted files displayed as a shell error, and its --wait as "Background shell
// failed"). The verdict is in the OUTPUT; non-zero is reserved for plumbing that genuinely broke
// (API unreachable, xell unresolvable).
let r = await check();
let v = json(r);
if (r.code >= 400) { console.log(`ooney check failed: ${v.error || r.code}`); process.exit(1); }
render(v);

if (!waitArg || v.verdict === 'deny' || v.verdict === 'live') {
  process.exit(0);
}

const deadline = Date.now() + waitSecs * 1000;
let lastGate = v.next?.gate + ':' + v.next?.verdict;
while (Date.now() < deadline) {
  await sleep(5000);
  r = await check().catch(() => null);
  if (!r) continue;
  v = json(r);
  if (r.code >= 400) { console.log(`  ✗ ${v.error || r.code}`); process.exit(1); }
  const g = v.next?.gate + ':' + v.next?.verdict;
  if (g !== lastGate) { render(v); lastGate = g; }
  if (v.verdict === 'live' || v.verdict === 'deny') process.exit(0);   // verdict delivered = success
}
console.log(`\n  ✗ TIMEOUT after ${waitSecs}s — still waiting (likely on a human). Re-run to resume.\n`);
process.exit(1);
